services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      target: ${NODE_ENV:-development}
    env_file:
      - .env
    volumes:
      - ./:/app
      - node_modules:/app/node_modules
      - build:/app/build
      - public:/app/public
    ports:
      - '3333:3333'
    depends_on:
      - db

  db:
    image: postgres:16-alpine
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      TZ: America/Sao_Paulo
    ports:
      - '5432:5432'

volumes:
  node_modules:
  postgres_data:
  build:
  public:
